version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    restart: always
    image: node:12
    working_dir: /usr/src/api-typescript-clean
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist:/usr/src/api-typescript-clean/dist
      - ./package.json:/usr/src/api-typescript-clean/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongo